DROP DATABASE IF EXISTS dvdrental;
CREATE DATABASE dvdrental;

ALTER ROLE "postgres" WITH LOGIN;
ALTER USER postgres REPLICATION;
ALTER ROLE postgres WITH SUPERUSER CREATEDB CREATEROLE LOGIN ENCRYPTED PASSWORD 'postgres';
